### ISSUE TITLE
Add support for parsing ndjson content-type

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio-apps/reactivesearch-proxy-server#1]
Starting `v2.5.0`, the library makes all requests using the /_msearch endpoint which requires the server to parse nd-json content.

We need to add support for it - the default json parsing middleware would fail.

An example of how this can look:

```
// to support JSON-encoded bodies
app.middleware('parse', bodyParser.json({
 limit: '50mb'
}));
// to support x-ndjson
app.middleware('parse', bodyParser.text({
 type: 'application/x-ndjson'
}));
```

**Comment by divyanshu013** [comment]
This proxy server only forwards the requests to and fro. However if someone were parsing the requests, the setup in the OP should work.
